# Generated by Django 3.0.3 on 2020-07-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takenumbers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestellnummer',
            name='bnum',
            field=models.CharField(default=1, max_length=10, unique=True),
        ),
    ]
