# Generated by Django 3.0.3 on 2020-07-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takenumbers', '0002_auto_20200727_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestellnummer',
            name='bnum',
            field=models.IntegerField(default=1, max_length=5, unique=True),
        ),
    ]
